<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O9F17IQ" failures="1" tests="1" name="testCases.TC_016_EditFundManagerDetailsTest" time="25.670" errors="0" timestamp="2025-03-27T16:57:16 IST" skipped="0">
  <testcase classname="testCases.TC_016_EditFundManagerDetailsTest" name="testDuplicateMobileNumberValidation" time="25.670">
    <failure message="Test failedExpected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator &#039;By.xpath: //div[@role=&#039;alert&#039; and contains(text(), &#039;Fund manager Updated Successfully&#039;)]&#039; (tried for 5 second(s) with 500 milliseconds interval)" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failedExpected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.xpath: //div[@role='alert' and contains(text(), 'Fund manager Updated Successfully')]' (tried for 5 second(s) with 500 milliseconds interval)
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_016_EditFundManagerDetailsTest.testDuplicateMobileNumberValidation(TC_016_EditFundManagerDetailsTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testDuplicateMobileNumberValidation -->
</testsuite> <!-- testCases.TC_016_EditFundManagerDetailsTest -->
